# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
image:
  - Ubuntu
  - Visual Studio 2017

# Install scripts. (runs after repo cloning)
install:
  - cmd: powershell Install-Product node $env:nodejs_version
  - sh: nvm install $nodejs_version
  - yarn --frozen-lockfile --non-interactive

cache:
  - '%LOCALAPPDATA%\Yarn'

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - yarn --version
  - git rev-parse HEAD
  - yarn test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
